### ISSUE TITLE
web idp_test: StatusInvalidNameidPolicy throws exception and fails to produce browser response.

### ISSUE THREAD

**Issue by rhoerbe** [identinetics/saml2test2#10]
traceback
```
/home/r2h2/virtualenv/saml2test2/bin/python /home/r2h2/devl/deploy/identinetics/docker-saml2test2/install/opt/saml2test2/script/idp_test.py -T /home/r2h2/devl/deploy/identinetics/docker-saml2test2/install/opt/saml2test2/testtool/idp_test/wb/test_tool.yaml /home/r2h2/devl/deploy/identinetics/docker-saml2test2/install/opt/saml2test2/testtool/idp_test/wb/conf.py
SP listening on port:8087
ServiceProviderRequestHandlerError('StatusInvalidNameidPolicy: An error occurred. from urn:oasis:names:tc:SAML:2.0:status:Requester',)
Traceback (most recent call last):
  File "/home/r2h2/devl/deploy/identinetics/docker-saml2test2/install/opt/saml2test2/src/saml2test/idp_test/wb_request.py", line 121, in handle_response
    response_args["outstanding"])
  File "/home/r2h2/virtualenv/saml2test2/lib/python3.4/site-packages/pysaml2-4.0.5-py3.4.egg/saml2/client_base.py", line 597, in parse_authn_request_response
    binding, **kwargs)
  File "/home/r2h2/virtualenv/saml2test2/lib/python3.4/site-packages/pysaml2-4.0.5-py3.4.egg/saml2/entity.py", line 1172, in _parse_response
    response = response.verify(keys)
  File "/home/r2h2/virtualenv/saml2test2/lib/python3.4/site-packages/pysaml2-4.0.5-py3.4.egg/saml2/response.py", line 1005, in verify
    res = self._verify()
  File "/home/r2h2/virtualenv/saml2test2/lib/python3.4/site-packages/pysaml2-4.0.5-py3.4.egg/saml2/response.py", line 408, in _verify
    assert self.status_ok()
  File "/home/r2h2/virtualenv/saml2test2/lib/python3.4/site-packages/pysaml2-4.0.5-py3.4.egg/saml2/response.py", line 370, in status_ok
    "%s from %s" % (msg, status.status_code.value,))
saml2.response.StatusInvalidNameidPolicy: An error occurred. from urn:oasis:names:tc:SAML:2.0:status:Requester

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/r2h2/virtualenv/saml2test2/lib/python3.4/site-packages/cherrypy/wsgiserver/wsgiserver3.py", line 1089, in communicate
    req.respond()
  File "/home/r2h2/virtualenv/saml2test2/lib/python3.4/site-packages/cherrypy/wsgiserver/wsgiserver3.py", line 877, in respond
    self.server.gateway(self).respond()
  File "/home/r2h2/virtualenv/saml2test2/lib/python3.4/site-packages/cherrypy/wsgiserver/wsgiserver3.py", line 1980, in respond
    response = self.req.server.wsgi_app(self.env, self.start_response)
  File "/home/r2h2/virtualenv/saml2test2/lib/python3.4/site-packages/Beaker-1.8.0-py3.4.egg/beaker/middleware.py", line 155, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/home/r2h2/devl/deploy/identinetics/docker-saml2test2/install/opt/saml2test2/script/idp_test.py", line 192, in application
    return do_next(tester, resp, sh, inut, filename, path)
  File "/home/r2h2/devl/deploy/identinetics/docker-saml2test2/install/opt/saml2test2/script/idp_test.py", line 46, in do_next
    tester.handle_response(resp, {})
  File "/home/r2h2/devl/deploy/identinetics/docker-saml2test2/install/opt/saml2test2/src/saml2test/idp_test/wb_tool.py", line 96, in handle_response
    return _oper.handle_response(resp)
  File "/home/r2h2/devl/deploy/identinetics/docker-saml2test2/install/opt/saml2test2/src/saml2test/idp_test/wb_request.py", line 194, in handle_response
    self.request_inst.handle_response(result, self.response_args)
  File "/home/r2h2/devl/deploy/identinetics/docker-saml2test2/install/opt/saml2test2/src/saml2test/idp_test/wb_request.py", line 126, in handle_response
    raise ServiceProviderRequestHandlerError(message)
saml2test.request.ServiceProviderRequestHandlerError: StatusInvalidNameidPolicy: An error occurred. from urn:oasis:names:tc:SAML:2.0:status:Requester
/home/r2h2/virtualenv/saml2test2/bin/python /home/r2h2/devl/deploy/identinetics/docker-saml2test2/install/opt/saml2test2/script/idp_test.py -T /home/r2h2/devl/deploy/identinetics/docker-saml2test2/install/opt/saml2test2/testtool/idp_test/wb/test_tool.yaml /home/r2h2/devl/deploy/identinetics/docker-saml2test2/install/opt/saml2test2/testtool/idp_test/wb/conf.py
SP listening on port:8087
ServiceProviderRequestHandlerError('StatusInvalidNameidPolicy: An error occurred. from urn:oasis:names:tc:SAML:2.0:status:Requester',)
Traceback (most recent call last):
  File "/home/r2h2/devl/deploy/identinetics/docker-saml2test2/install/opt/saml2test2/src/saml2test/idp_test/wb_request.py", line 121, in handle_response
    response_args["outstanding"])
  File "/home/r2h2/virtualenv/saml2test2/lib/python3.4/site-packages/pysaml2-4.0.5-py3.4.egg/saml2/client_base.py", line 597, in parse_authn_request_response
    binding, **kwargs)
  File "/home/r2h2/virtualenv/saml2test2/lib/python3.4/site-packages/pysaml2-4.0.5-py3.4.egg/saml2/entity.py", line 1172, in _parse_response
    response = response.verify(keys)
  File "/home/r2h2/virtualenv/saml2test2/lib/python3.4/site-packages/pysaml2-4.0.5-py3.4.egg/saml2/response.py", line 1005, in verify
    res = self._verify()
  File "/home/r2h2/virtualenv/saml2test2/lib/python3.4/site-packages/pysaml2-4.0.5-py3.4.egg/saml2/response.py", line 408, in _verify
    assert self.status_ok()
  File "/home/r2h2/virtualenv/saml2test2/lib/python3.4/site-packages/pysaml2-4.0.5-py3.4.egg/saml2/response.py", line 370, in status_ok
    "%s from %s" % (msg, status.status_code.value,))
saml2.response.StatusInvalidNameidPolicy: An error occurred. from urn:oasis:names:tc:SAML:2.0:status:Requester

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/r2h2/virtualenv/saml2test2/lib/python3.4/site-packages/cherrypy/wsgiserver/wsgiserver3.py", line 1089, in communicate
    req.respond()
  File "/home/r2h2/virtualenv/saml2test2/lib/python3.4/site-packages/cherrypy/wsgiserver/wsgiserver3.py", line 877, in respond
    self.server.gateway(self).respond()
  File "/home/r2h2/virtualenv/saml2test2/lib/python3.4/site-packages/cherrypy/wsgiserver/wsgiserver3.py", line 1980, in respond
    response = self.req.server.wsgi_app(self.env, self.start_response)
  File "/home/r2h2/virtualenv/saml2test2/lib/python3.4/site-packages/Beaker-1.8.0-py3.4.egg/beaker/middleware.py", line 155, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/home/r2h2/devl/deploy/identinetics/docker-saml2test2/install/opt/saml2test2/script/idp_test.py", line 192, in application
    return do_next(tester, resp, sh, inut, filename, path)
  File "/home/r2h2/devl/deploy/identinetics/docker-saml2test2/install/opt/saml2test2/script/idp_test.py", line 46, in do_next
    tester.handle_response(resp, {})
  File "/home/r2h2/devl/deploy/identinetics/docker-saml2test2/install/opt/saml2test2/src/saml2test/idp_test/wb_tool.py", line 96, in handle_response
    return _oper.handle_response(resp)
  File "/home/r2h2/devl/deploy/identinetics/docker-saml2test2/install/opt/saml2test2/src/saml2test/idp_test/wb_request.py", line 194, in handle_response
    self.request_inst.handle_response(result, self.response_args)
  File "/home/r2h2/devl/deploy/identinetics/docker-saml2test2/install/opt/saml2test2/src/saml2test/idp_test/wb_request.py", line 126, in handle_response
    raise ServiceProviderRequestHandlerError(message)
saml2test.request.ServiceProviderRequestHandlerError: StatusInvalidNameidPolicy: An error occurred. from urn:oasis:names:tc:SAML:2.0:status:Requester
```

**Comment by rhoerbe** [comment]
The problem is, that wb_request.py is not producing a proper HTTP response if pysaml2 throws an exception. 

Also, pysaml2 should be more verbose about the failure (which nameid policies received, which expected), but that is a minor inconvenience.

**Comment by rhoerbe** [comment]
In the course of this problem, the response status should make a difference between "Test not run" and "Test run but failed due to a test tool problem"

**Comment by rhoerbe** [comment]
implemented in websso-02
