### ISSUE TITLE
aatest throwing exception instead of reporting error in the log file

### ISSUE THREAD

**Issue by rhoerbe** [identinetics/saml2test2#62]
websso-04:

idp_test on stderr:

```
Exception('ERROR Assertion verification had gone wrong.',)
Traceback (most recent call last):
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/saml2test-1.0.1b0-py3.4.egg/EGG-INFO/scripts/idp_test.py", line 101, in do_next
    _ver.test_sequence(tester.conv.flow["assert"])
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/aatest-0.1.0-py3.4.egg/aatest/verify.py", line 97, in test_sequence
    self.do_check(test, **kwargs)
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/aatest-0.1.0-py3.4.egg/aatest/verify.py", line 79, in do_check
    self.check_severity(stat)
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/aatest-0.1.0-py3.4.egg/aatest/verify.py", line 50, in check_severity
    raise Break(stat.message)
aatest.Break: The IdP returns wrong NameID format
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/cherrypy/wsgiserver/__init__.py", line 1405, in communicate
    req.respond()
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/cherrypy/wsgiserver/__init__.py", line 859, in respond
    self.server.gateway(self).respond()
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/cherrypy/wsgiserver/__init__.py", line 2310, in respond
    response = self.req.server.wsgi_app(self.env, self.start_response)
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/beaker/middleware.py", line 155, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/saml2test-1.0.1b0-py3.4.egg/EGG-INFO/scripts/idp_test.py", line 303, in application
    html_page = do_next(tester, resp, sh, inut, filename, path)
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/saml2test-1.0.1b0-py3.4.egg/EGG-INFO/scripts/idp_test.py", line 111, in do_next
    raise Exception(msg)
Exception: ERROR Assertion verification had gone wrong.
```

**Comment by rhoerbe** [comment]
cause in flows.yaml for websso-04err:

set_request_args:
              name_id.format: ... persistent
verify_subject:
        name_id.format: ... transient

This test is not very sensible, but should not cause a white screen of death
